# Generated by Django 4.2.20 on 2025-04-14 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('D', 'DEPOSIT'), ('W', 'WITHDRAW'), ('T', 'TRANSFER'), ('B', 'BALANCE')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='ref_<function uuid4 at 0x0000012580814AF0>', max_length=40, unique=True),
        ),
    ]
