# Generated by Django 4.2.20 on 2025-04-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_transaction_name_remove_transaction_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='ref_<function uuid4 at 0x00000239B2FABAF0>', max_length=40, unique=True),
        ),
    ]
