# Generated by Django 4.2.20 on 2025-04-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='ref_<function uuid4 at 0x000001D1BE66AAF0>', max_length=40, unique=True),
        ),
    ]
