# Generated by Django 4.2.20 on 2025-04-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_alter_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='ref_<function uuid4 at 0x00000131E52B8A60>', max_length=40, unique=True),
        ),
    ]
